#== contains input/output parameters that can be tweaked
#Incoming file
file_type: csv
dataset_name: cancerfile
file_name: cancerdata
inbound_delimiter: ","
skip_leading_rows: 1


#outbound file    
outbound_delimiter: "|"
columns:
    - patient
    - a1
    - a2
    - a3
    - a4
    - a5
    - a6
    - a7
    - a8
    - a9
    - a10
    - diagnosis
